liste = [1,45,46,7,48,50,2,3,4,5,6]

print(liste)
print(liste[0])
print(liste[len(liste)-1])
print(liste[-1])
print(liste[(len(liste) - 1)//2])
print(sum(liste))
print(sum(liste)/len(liste))
liste.sort()
print(liste)
liste.sort(reverse=True)
print(liste)
print(min(liste))
print(max(liste))
print(liste)
liste.append(15)
print(liste)
liste.insert(3,100)
print(liste)
liste.remove(4)
print(liste)
print(liste.pop(0))
print(liste)
print(liste.pop())
print(liste)
